# Site Settings
title: Tutorials
description: Analysis of system-level stability and hardware-level security remediations.

# My Tutorials
baseurl: "/tutorials" 
url: "https://shadowpbx.github.io"

# Build Settings
remote_theme: "mmistakes/minimal-mistakes"
future: true
timezone: America/New_York

author:
  name   : "Tanvir Hussain"
  avatar : "/assets/images/avatar.webp" # Or a tech-themed avatar
  bio    : "Cybersecurity Student | Home Lab Enthusiast"
  location: "New York"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/shadowpbx"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true # This is the "magic" line that turns on the sidebar
      read_time: false
      comments: false
      share: true
      related: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
